### ISSUE TITLE
Why is there no way to save the "guild settings"?

### ISSUE THREAD

**Issue by TheSameIdea** [fuma-nama/discord-bot-dashboard-next#32]
Title pretty much says it all, however, there is no current way to save guild settings, was this intentional? 
![image](https://github.com/SonMooSans/discord-bot-dashboard-next/assets/71250510/5ce787b8-a6ea-472b-9e96-23e312a58bd3)

**Comment by SonMooSans** [comment]
It's just a showcase which has no functionality.
