### ISSUE TITLE
Trying to figure out backend server

### ISSUE THREAD

**Issue by evanpurl** [fuma-nama/discord-bot-dashboard-next#37]
Hi there!

I followed the tutorial and have gotten stuck on the backend server part of it. The [official example](https://github.com/fuma-nama/discord-bot-dashboard-next#official-example) link doesn't go anywhere, so I figured I would ask here if there is some example server I could learn from.

Thanks!

**Comment by fuma-nama** [comment]
Seems like some redirect links are broken since my name is changed. Here's the working one: https://github.com/fuma-nama/discord-dashboard-backend-next
