### ISSUE TITLE
use design on other project?

### ISSUE THREAD

**Issue by 0RE0NE0** [fuma-nama/discord-bot-dashboard-next#50]
Hey, I wanted to ask if I can use your design on my own dashboard, because I use js and react instead of ts and next and I don't understand some things like your queries, so I'm reprogramming it for myself and just wanted to know if I need a new design xD

**Comment by fuma-nama** [comment]
feel sure to use it as an inspiration! I'm currently busy at other things so probably won't be active on this project anymore.
